version: '3'
services:
  flask:
      container_name: flask
      image: "flask:test"
      ports:
       - "5000:5000"
      networks:
      - backend
  nginx:
      container_name: nginx
      image: "nginx:test"
      ports:
       - "80:80"
      networks:
       - backend
  postgres1:
      container_name: postgres1
      image: "jjangue/postgres:latest"
      privileged: true
      ports:
       - "5432:5432"
      environment:
       - POSTGRES_PASSWORD=1234
      networks:
       - backend

networks:
  backend:
    driver: bridge
